//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministradorCursos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public int idFactura { get; set; }
        public int idDetalleFactura { get; set; }
        public int idAlumno { get; set; }
        public int idTipoPago { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual DetalleFactura DetalleFactura { get; set; }
        public virtual TipoPago TipoPago { get; set; }
    }
}
